#!/usr/bin/env python3.8
# @generated by pegen from src/magic_codec/grammar/macro_peg.peg

import ast
import sys
import tokenize

from typing import Any, Optional

from pegen.parser import memoize, memoize_left_rec, logger, Parser

import textwrap
from magic_codec.parser.peg import *
from tokenize import TokenInfo

def source_range(tokenizer, lineno, col_offset, end_lineno, end_col_offset):
    lines = tokenizer.get_lines(list(range(lineno, end_lineno + 1)))
    lines[-1] = lines[-1][:end_col_offset - 1]
    lines[0] = lines[0][col_offset + 1:]

    # strip leading whitespace
    data = ''.join(lines).lstrip(' ')
    if data[0] == '\n':
        data = data[1:]
    return textwrap.dedent(data)

class MacroPegParser(PegParser, ):

    @memoize
    def action(self) -> Optional[str]:
        # action: "{" ~ target_atoms "}"
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        cut = False
        if (
            (self.expect("{"))
            and
            (cut := True)
            and
            (self.target_atoms())
            and
            (self.expect("}"))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return source_range ( self . _tokenizer , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if cut:
            return None;
        return None;

    KEYWORDS = tuple(set([*(), *getattr(PegParser, 'KEYWORDS', [])]))
    SOFT_KEYWORDS = tuple(set([*(), *getattr(PegParser, 'SOFT_KEYWORDS', [])]))
    RULES = tuple(set(['action', *getattr(PegParser, 'KEYWORDS', [])]))

