#!/usr/bin/env python3.8
# @generated by pegen from src/magic_codec/parser/macro_peg.peg

import ast
import sys
import tokenize

from typing import Any, Optional

from pegen.parser import memoize, memoize_left_rec, logger, Parser

from magic_codec.parser.peg import *

class Fragment:
    def __init__(self, *args):
        self.args = args

    def __repr__(self):
        return ', '.join(repr(arg) for arg in self.args)

class MacroPegParser(PegParser, ):

    @memoize
    def ANY(self) -> Optional[Any]:
        # ANY: ~
        mark = self._mark()
        cut = False
        if (
            (cut := True)
        ):
            return t if ( t := self . _tokenizer . getnext ( ) ) . type != 0 else None;
        self._reset(mark)
        if cut:
            return None;
        return None;

    @memoize
    def braces(self) -> Optional[Any]:
        # braces: '(' | ')' | '[' | ']' | '{' | '}'
        mark = self._mark()
        if (
            (literal := self.expect('('))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect(')'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('['))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect(']'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('{'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('}'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def action(self) -> Optional[list]:
        # action: '{' ~ fragment '}'
        mark = self._mark()
        cut = False
        if (
            (self.expect('{'))
            and
            (cut := True)
            and
            (t := self.fragment())
            and
            (self.expect('}'))
        ):
            return t;
        self._reset(mark)
        if cut:
            return None;
        return None;

    @memoize
    def replacement(self) -> Optional[Any]:
        # replacement: '$' NAME
        mark = self._mark()
        if (
            (a := self.expect('$'))
            and
            (b := self.name())
        ):
            return [a , b];
        self._reset(mark)
        return None;

    @memoize
    def fragment(self) -> Optional[str]:
        # fragment: fragment_atom fragment | fragment_atom
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (self.fragment_atom())
            and
            (b := self.fragment())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return Fragment ( lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , next_frag = b );
        self._reset(mark)
        if (
            (self.fragment_atom())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return Fragment ( lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        return None;

    @memoize
    def fragment_atom(self) -> Optional[str]:
        # fragment_atom: "{" ~ fragment? "}" | "[" ~ fragment? "]" | NAME | NUMBER | STRING | FSTRING_START fragment_fstring_middle* FSTRING_END | !"}" !"]" OP
        mark = self._mark()
        cut = False
        if (
            (a := self.expect("{"))
            and
            (cut := True)
            and
            (atoms := self.fragment(),)
            and
            (b := self.expect("}"))
        ):
            return [a, atoms, b];
        self._reset(mark)
        if cut:
            return None;
        cut = False
        if (
            (a := self.expect("["))
            and
            (cut := True)
            and
            (atoms := self.fragment(),)
            and
            (b := self.expect("]"))
        ):
            return [a, atoms, b];
        self._reset(mark)
        if cut:
            return None;
        if (
            (name := self.name())
        ):
            return name;
        self._reset(mark)
        if (
            (number := self.number())
        ):
            return number;
        self._reset(mark)
        if (
            (string := self.string())
        ):
            return string;
        self._reset(mark)
        if (
            (l := self.fstring_start())
            and
            (m := self._loop0_1001(),)
            and
            (r := self.fstring_end())
        ):
            return [l, m, r];
        self._reset(mark)
        if (
            (self.negative_lookahead(self.expect, "}"))
            and
            (self.negative_lookahead(self.expect, "]"))
            and
            (op := self.op())
        ):
            return op;
        self._reset(mark)
        return None;

    @memoize
    def fragment_fstring_middle(self) -> Optional[str]:
        # fragment_fstring_middle: FSTRING_MIDDLE | "{" | "}" | fragment_atom
        mark = self._mark()
        if (
            (fstring_middle := self.fstring_middle())
        ):
            return fstring_middle;
        self._reset(mark)
        if (
            (literal := self.expect("{"))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect("}"))
        ):
            return literal;
        self._reset(mark)
        if (
            (fragment_atom := self.fragment_atom())
        ):
            return fragment_atom;
        self._reset(mark)
        return None;

    @memoize
    def _loop0_1001(self) -> Optional[Any]:
        # _loop0_1001: fragment_fstring_middle
        mark = self._mark()
        children = []
        while (
            (fragment_fstring_middle := self.fragment_fstring_middle())
        ):
            children.append(fragment_fstring_middle)
            mark = self._mark()
        self._reset(mark)
        return children;

    KEYWORDS = tuple(set([*(), *getattr(PegParser, 'KEYWORDS', [])]))
    SOFT_KEYWORDS = tuple(set([*(), *getattr(PegParser, 'SOFT_KEYWORDS', [])]))
    RULES = tuple(set(['ANY', 'braces', 'action', 'replacement', 'fragment', 'fragment_atom', 'fragment_fstring_middle', *getattr(PegParser, 'KEYWORDS', [])]))

