#!/usr/bin/env python3.8
# @generated by pegen from src/magic_codec/parser/macro.peg

import ast
import sys
import tokenize

from typing import Any, Optional

from pegen.parser import memoize, memoize_left_rec, logger, Parser

from magic_codec.macro.parser import *
from magic_codec.macro.macro_ast import *
from token import NAME, ENDMARKER
from magic_codec.parser.python import PythonParser

class MacroParser(PythonParser, ):

    @memoize
    def KEYWORD(self) -> Optional[Any]:
        # KEYWORD: ~
        mark = self._mark()
        cut = False
        if (
            (cut := True)
        ):
            return ( self . _tokenizer . getnext ( ) if ( tok := self . _tokenizer . peek ( ) ) . type == NAME and tok . string in self . KEYWORDS else None );
        self._reset(mark)
        if cut:
            return None;
        return None;

    @memoize
    def ANY(self) -> Optional[Any]:
        # ANY: ~
        mark = self._mark()
        cut = False
        if (
            (cut := True)
        ):
            return t if ( t := self . _tokenizer . getnext ( ) ) . type != 0 else None;
        self._reset(mark)
        if cut:
            return None;
        return None;

    @memoize
    def braces(self) -> Optional[Any]:
        # braces: '(' | ')' | '[' | ']' | '{' | '}'
        mark = self._mark()
        if (
            (literal := self.expect('('))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect(')'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('['))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect(']'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('{'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('}'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def simple_stmt(self) -> Optional[Any]:
        # simple_stmt: assignment | &"type" type_alias | macro_name '(' args_fragment? ')' | star_expressions | &'return' return_stmt | &('import' | 'from') import_stmt | &'raise' raise_stmt | &'pass' pass_stmt | &'del' del_stmt | &'yield' yield_stmt | &'assert' assert_stmt | &'break' break_stmt | &'continue' continue_stmt | &'global' global_stmt | &'nonlocal' nonlocal_stmt
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (assignment := self.assignment())
        ):
            return assignment;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, "type"))
            and
            (type_alias := self.type_alias())
        ):
            return type_alias;
        self._reset(mark)
        if (
            (a := self.macro_name())
            and
            (self.expect('('))
            and
            (args := self.args_fragment(),)
            and
            (self.expect(')'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return MacroCall ( func = a . id , args = args or [] , keywords = [] , expand_as_stmts = True , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , );
        self._reset(mark)
        if (
            (e := self.star_expressions())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Expr ( value = e , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'return'))
            and
            (return_stmt := self.return_stmt())
        ):
            return return_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self._tmp_1001, ))
            and
            (import_stmt := self.import_stmt())
        ):
            return import_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'raise'))
            and
            (raise_stmt := self.raise_stmt())
        ):
            return raise_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'pass'))
            and
            (pass_stmt := self.pass_stmt())
        ):
            return pass_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'del'))
            and
            (del_stmt := self.del_stmt())
        ):
            return del_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'yield'))
            and
            (yield_stmt := self.yield_stmt())
        ):
            return yield_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'assert'))
            and
            (assert_stmt := self.assert_stmt())
        ):
            return assert_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'break'))
            and
            (break_stmt := self.break_stmt())
        ):
            return break_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'continue'))
            and
            (continue_stmt := self.continue_stmt())
        ):
            return continue_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'global'))
            and
            (global_stmt := self.global_stmt())
        ):
            return global_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'nonlocal'))
            and
            (nonlocal_stmt := self.nonlocal_stmt())
        ):
            return nonlocal_stmt;
        self._reset(mark)
        return None;

    @memoize
    def compound_stmt(self) -> Optional[Any]:
        # compound_stmt: macro_stmt | &('def' | '@' | 'async') function_def | &'if' if_stmt | &('class' | '@') class_def | &('with' | 'async') with_stmt | &('for' | 'async') for_stmt | &'try' try_stmt | &'while' while_stmt | match_stmt
        mark = self._mark()
        if (
            (macro_stmt := self.macro_stmt())
        ):
            return macro_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self._tmp_1002, ))
            and
            (function_def := self.function_def())
        ):
            return function_def;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'if'))
            and
            (if_stmt := self.if_stmt())
        ):
            return if_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self._tmp_1003, ))
            and
            (class_def := self.class_def())
        ):
            return class_def;
        self._reset(mark)
        if (
            (self.positive_lookahead(self._tmp_1004, ))
            and
            (with_stmt := self.with_stmt())
        ):
            return with_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self._tmp_1005, ))
            and
            (for_stmt := self.for_stmt())
        ):
            return for_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'try'))
            and
            (try_stmt := self.try_stmt())
        ):
            return try_stmt;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'while'))
            and
            (while_stmt := self.while_stmt())
        ):
            return while_stmt;
        self._reset(mark)
        if (
            (match_stmt := self.match_stmt())
        ):
            return match_stmt;
        self._reset(mark)
        return None;

    @memoize
    def unparsed_atoms(self) -> Optional[Any]:
        # unparsed_atoms: ((!NEWLINE !INDENT !DEDENT ANY))+
        mark = self._mark()
        if (
            (a := self._loop1_1006())
        ):
            return a;
        self._reset(mark)
        return None;

    @memoize
    def unparsed_balanced(self) -> Optional[Any]:
        # unparsed_balanced: '(' unparsed_balanced? ')' unparsed_balanced? | '[' unparsed_balanced? ']' unparsed_balanced? | '{' unparsed_balanced? '}' unparsed_balanced? | ((!braces !NEWLINE ANY))+ unparsed_balanced?
        mark = self._mark()
        if (
            (literal := self.expect('('))
            and
            (opt := self.unparsed_balanced(),)
            and
            (literal_1 := self.expect(')'))
            and
            (opt_1 := self.unparsed_balanced(),)
        ):
            return [literal, opt, literal_1, opt_1];
        self._reset(mark)
        if (
            (literal := self.expect('['))
            and
            (opt := self.unparsed_balanced(),)
            and
            (literal_1 := self.expect(']'))
            and
            (opt_1 := self.unparsed_balanced(),)
        ):
            return [literal, opt, literal_1, opt_1];
        self._reset(mark)
        if (
            (literal := self.expect('{'))
            and
            (opt := self.unparsed_balanced(),)
            and
            (literal_1 := self.expect('}'))
            and
            (opt_1 := self.unparsed_balanced(),)
        ):
            return [literal, opt, literal_1, opt_1];
        self._reset(mark)
        if (
            (_loop1_1007 := self._loop1_1007())
            and
            (opt := self.unparsed_balanced(),)
        ):
            return [_loop1_1007, opt];
        self._reset(mark)
        return None;

    @memoize
    def unparsed_line(self) -> Optional[Any]:
        # unparsed_line: unparsed_atoms NEWLINE
        mark = self._mark()
        if (
            (unparsed_atoms := self.unparsed_atoms())
            and
            (_newline := self.expect('NEWLINE'))
        ):
            return [unparsed_atoms, _newline];
        self._reset(mark)
        return None;

    @memoize
    def unparsed_block(self) -> Optional[Any]:
        # unparsed_block: INDENT unparsed_block+ DEDENT | unparsed_line
        mark = self._mark()
        if (
            (_indent := self.expect('INDENT'))
            and
            (_loop1_1008 := self._loop1_1008())
            and
            (_dedent := self.expect('DEDENT'))
        ):
            return [_indent, _loop1_1008, _dedent];
        self._reset(mark)
        if (
            (unparsed_line := self.unparsed_line())
        ):
            return unparsed_line;
        self._reset(mark)
        return None;

    @memoize
    def args_fragment(self) -> Optional[Any]:
        # args_fragment: unparsed_balanced
        mark = self._mark()
        if (
            (a := self.unparsed_balanced())
        ):
            return self . make_fragment ( a );
        self._reset(mark)
        return None;

    @memoize
    def suite_fragment(self) -> Optional[Any]:
        # suite_fragment: NEWLINE INDENT unparsed_block+ DEDENT | unparsed_line
        mark = self._mark()
        if (
            (self.expect('NEWLINE'))
            and
            (self.expect('INDENT'))
            and
            (a := self._loop1_1009())
            and
            (self.expect('DEDENT'))
        ):
            return self . make_fragment ( a );
        self._reset(mark)
        if (
            (a := self.unparsed_line())
        ):
            return self . make_fragment ( a );
        self._reset(mark)
        return None;

    @memoize
    def raw_macro_stmt_args(self) -> Optional[Any]:
        # raw_macro_stmt_args: '(' unparsed_balanced? ')' raw_macro_stmt_args? | '[' unparsed_balanced? ']' raw_macro_stmt_args? | '{' unparsed_balanced? '}' raw_macro_stmt_args? | ((!braces !':' !NEWLINE ANY))+ raw_macro_stmt_args?
        mark = self._mark()
        if (
            (a := self.expect('('))
            and
            (b := self.unparsed_balanced(),)
            and
            (c := self.expect(')'))
            and
            (opt := self.raw_macro_stmt_args(),)
        ):
            return [a, b, c, opt];
        self._reset(mark)
        if (
            (a := self.expect('['))
            and
            (b := self.unparsed_balanced(),)
            and
            (c := self.expect(']'))
            and
            (opt := self.raw_macro_stmt_args(),)
        ):
            return [a, b, c, opt];
        self._reset(mark)
        if (
            (a := self.expect('{'))
            and
            (b := self.unparsed_balanced(),)
            and
            (c := self.expect('}'))
            and
            (opt := self.raw_macro_stmt_args(),)
        ):
            return [a, b, c, opt];
        self._reset(mark)
        if (
            (a := self._loop1_1010())
            and
            (opt := self.raw_macro_stmt_args(),)
        ):
            return [a, opt];
        self._reset(mark)
        return None;

    @memoize
    def macro_stmt_args(self) -> Optional[Any]:
        # macro_stmt_args: raw_macro_stmt_args
        mark = self._mark()
        if (
            (a := self.raw_macro_stmt_args())
        ):
            return self . make_fragment ( a );
        self._reset(mark)
        return None;

    @memoize
    def macro_stmt(self) -> Optional[MacroCall]:
        # macro_stmt: macro_name macro_stmt_args? ':' unparsed_line INDENT | macro_name ':' suite_fragment | macro_name macro_stmt_args ':' suite_fragment
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (self.macro_name())
            and
            (self.macro_stmt_args(),)
            and
            (self.expect(':'))
            and
            (self.unparsed_line())
            and
            (self.expect('INDENT'))
        ):
            return self . raise_indentation_error ( "unexpected indented block" );
        self._reset(mark)
        if (
            (a := self.macro_name())
            and
            (self.expect(':'))
            and
            (b := self.suite_fragment())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return MacroCall ( a , args = b , expand_as_stmts = True , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (a := self.macro_name())
            and
            (h := self.macro_stmt_args())
            and
            (self.expect(':'))
            and
            (b := self.suite_fragment())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return MacroCall ( MacroCall ( a , args = h , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset ) , b , expand_as_stmts = True , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        return None;

    @memoize
    def forbidden_macro_keywords(self) -> Optional[Any]:
        # forbidden_macro_keywords: 'import' | 'from'
        mark = self._mark()
        if (
            (literal := self.expect('import'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('from'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def macro_name(self) -> Optional[Any]:
        # macro_name: (NAME | !forbidden_macro_keywords KEYWORD) '!'
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (a := self._tmp_1011())
            and
            (self.expect('!'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return MacroName ( id = a . string , ctx = Load , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        return None;

    @memoize
    def maybe_macro(self) -> Optional[Any]:
        # maybe_macro: macro_name | NAME
        mark = self._mark()
        if (
            (macro_name := self.macro_name())
        ):
            return macro_name;
        self._reset(mark)
        if (
            (name := self.name())
        ):
            return name;
        self._reset(mark)
        return None;

    @memoize
    def decorator(self) -> Optional[Any]:
        # decorator: ('@' dec_macro NEWLINE) | ('@' dec_maybe_call NEWLINE) | ('@' named_expression NEWLINE)
        mark = self._mark()
        if (
            (a := self._tmp_1012())
        ):
            return a;
        self._reset(mark)
        if (
            (a := self._tmp_1013())
        ):
            return a;
        self._reset(mark)
        if (
            (a := self._tmp_1014())
        ):
            return self . check_version ( ( 3 , 9 ) , "Generic decorator are" , a );
        self._reset(mark)
        return None;

    @memoize
    def dec_macro(self) -> Optional[Any]:
        # dec_macro: macro_name '(' args_fragment? ')' | macro_name | 'macro' '(' arguments? ')' | 'macro'
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (a := self.macro_name())
            and
            (self.expect('('))
            and
            (args := self.args_fragment(),)
            and
            (self.expect(')'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return MacroCall ( func = a . id , args = args or [] , keywords = [] , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (macro_name := self.macro_name())
        ):
            return macro_name;
        self._reset(mark)
        if (
            (a := self.expect('macro'))
            and
            (self.expect('('))
            and
            (z := self.arguments(),)
            and
            (self.expect(')'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Call ( func = ast . Name ( id = a . string , ctx = Load , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset ) , args = z [0] if z else [] , keywords = z [1] if z else [] , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (a := self.expect('macro'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Name ( id = a . string , ctx = Load , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        return None;

    @memoize
    def class_def(self) -> Optional[Union [ClassDef]]:
        # class_def: decorators &'class' | class_def_raw
        mark = self._mark()
        if (
            (a := self.decorators())
            and
            (self.positive_lookahead(self.expect, 'class'))
        ):
            return self . conditional_parse_def ( a , self . unparsed_class_def , self . class_def_raw );
        self._reset(mark)
        if (
            (class_def_raw := self.class_def_raw())
        ):
            return class_def_raw;
        self._reset(mark)
        return None;

    @memoize
    def class_def_raw(self) -> Optional[Union [ClassDef]]:
        # class_def_raw: invalid_class_def_raw | 'class' maybe_macro type_params? ['(' arguments? ')'] ':' block
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            self.call_invalid_rules
            and
            (self.invalid_class_def_raw())
        ):
            return None  # pragma: no cover;
        self._reset(mark)
        if (
            (self.expect('class'))
            and
            (a := self.maybe_macro())
            and
            (t := self.type_params(),)
            and
            (b := self._tmp_1015(),)
            and
            (self.expect(':'))
            and
            (c := self.block())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ( ClassDef ( a . string , bases = b [0] if b else [] , keywords = b [1] if b else [] , body = c , decorator_list = [] , type_params = t or [] , is_macro = isinstance ( a , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) if sys . version_info >= ( 3 , 12 ) else ClassDef ( a . string , bases = b [0] if b else [] , keywords = b [1] if b else [] , body = c , decorator_list = [] , is_macro = isinstance ( a , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) );
        self._reset(mark)
        return None;

    @memoize
    def unparsed_class_def(self) -> Optional[Union [ClassDef]]:
        # unparsed_class_def: invalid_class_def_raw | 'class' maybe_macro type_params? ['(' arguments? ')'] ':' suite_fragment
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            self.call_invalid_rules
            and
            (self.invalid_class_def_raw())
        ):
            return None  # pragma: no cover;
        self._reset(mark)
        if (
            (self.expect('class'))
            and
            (a := self.maybe_macro())
            and
            (t := self.type_params(),)
            and
            (b := self._tmp_1016(),)
            and
            (self.expect(':'))
            and
            (c := self.suite_fragment())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ( ClassDef ( a . string , bases = b [0] if b else [] , keywords = b [1] if b else [] , body = c , decorator_list = [] , type_params = t or [] , is_macro = isinstance ( a , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) if sys . version_info >= ( 3 , 12 ) else ClassDef ( a . string , bases = b [0] if b else [] , keywords = b [1] if b else [] , body = c , decorator_list = [] , is_macro = isinstance ( a , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) );
        self._reset(mark)
        return None;

    @memoize
    def function_def(self) -> Optional[Union [FunctionDef , AsyncFunctionDef]]:
        # function_def: decorators &('def' | 'async') | function_def_raw
        mark = self._mark()
        if (
            (d := self.decorators())
            and
            (self.positive_lookahead(self._tmp_1017, ))
        ):
            return self . conditional_parse_def ( d , self . unparsed_function_def , self . function_def_raw );
        self._reset(mark)
        if (
            (function_def_raw := self.function_def_raw())
        ):
            return function_def_raw;
        self._reset(mark)
        return None;

    @memoize
    def function_def_raw(self) -> Optional[Union [FunctionDef , AsyncFunctionDef]]:
        # function_def_raw: invalid_def_raw | 'def' maybe_macro type_params? '(' params? ')' ['->' expression] ':' func_type_comment? block | 'async' 'def' maybe_macro type_params? '(' params? ')' ['->' expression] ':' func_type_comment? block
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            self.call_invalid_rules
            and
            (self.invalid_def_raw())
        ):
            return None  # pragma: no cover;
        self._reset(mark)
        if (
            (self.expect('def'))
            and
            (n := self.maybe_macro())
            and
            (t := self.type_params(),)
            and
            (self.expect('('))
            and
            (params := self.params(),)
            and
            (self.expect(')'))
            and
            (a := self._tmp_1018(),)
            and
            (self.expect(':'))
            and
            (tc := self.func_type_comment(),)
            and
            (b := self.block())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ( FunctionDef ( name = n . string , args = params or self . make_arguments ( None , [] , None , [] , None ) , returns = a , body = b , type_comment = tc , type_params = t or [] , decorator_list = [] , is_macro = isinstance ( n , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) if sys . version_info >= ( 3 , 12 ) else FunctionDef ( name = n . string , args = params or self . make_arguments ( None , [] , None , [] , None ) , returns = a , body = b , type_comment = tc , decorator_list = [] , is_macro = isinstance ( n , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) );
        self._reset(mark)
        if (
            (self.expect('async'))
            and
            (self.expect('def'))
            and
            (n := self.maybe_macro())
            and
            (t := self.type_params(),)
            and
            (self.expect('('))
            and
            (params := self.params(),)
            and
            (self.expect(')'))
            and
            (a := self._tmp_1019(),)
            and
            (self.expect(':'))
            and
            (tc := self.func_type_comment(),)
            and
            (b := self.block())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ( self . check_version ( ( 3 , 5 ) , "Async functions are" , AsyncFunctionDef ( name = n . string , args = params or self . make_arguments ( None , [] , None , [] , None ) , returns = a , body = b , type_comment = tc , type_params = t or [] , decorator_list = [] , is_macro = isinstance ( n , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) ) if sys . version_info >= ( 3 , 12 ) else self . check_version ( ( 3 , 5 ) , "Async functions are" , AsyncFunctionDef ( name = n . string , args = params or self . make_arguments ( None , [] , None , [] , None ) , returns = a , body = b , type_comment = tc , decorator_list = [] , is_macro = isinstance ( n , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) ) );
        self._reset(mark)
        return None;

    @memoize
    def unparsed_function_def(self) -> Optional[Union [FunctionDef , AsyncFunctionDef]]:
        # unparsed_function_def: invalid_def_raw | 'def' maybe_macro type_params? '(' params? ')' ['->' expression] ':' func_type_comment? suite_fragment | 'async' 'def' maybe_macro type_params? &&'(' params? ')' ['->' expression] ':' func_type_comment? suite_fragment
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            self.call_invalid_rules
            and
            (self.invalid_def_raw())
        ):
            return None  # pragma: no cover;
        self._reset(mark)
        if (
            (self.expect('def'))
            and
            (n := self.maybe_macro())
            and
            (t := self.type_params(),)
            and
            (self.expect('('))
            and
            (params := self.params(),)
            and
            (self.expect(')'))
            and
            (a := self._tmp_1020(),)
            and
            (self.expect(':'))
            and
            (tc := self.func_type_comment(),)
            and
            (b := self.suite_fragment())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ( FunctionDef ( name = n . string , args = params or self . make_arguments ( None , [] , None , [] , None ) , returns = a , body = b , type_comment = tc , type_params = t or [] , decorator_list = [] , is_macro = isinstance ( n , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) if sys . version_info >= ( 3 , 12 ) else FunctionDef ( name = n . string , args = params or self . make_arguments ( None , [] , None , [] , None ) , returns = a , body = b , type_comment = tc , is_macro = isinstance ( n , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) );
        self._reset(mark)
        if (
            (self.expect('async'))
            and
            (self.expect('def'))
            and
            (n := self.maybe_macro())
            and
            (t := self.type_params(),)
            and
            (self.expect_forced(self.expect('('), "'('"))
            and
            (params := self.params(),)
            and
            (self.expect(')'))
            and
            (a := self._tmp_1021(),)
            and
            (self.expect(':'))
            and
            (tc := self.func_type_comment(),)
            and
            (b := self.suite_fragment())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ( self . check_version ( ( 3 , 5 ) , "Async functions are" , AsyncFunctionDef ( name = n . string , args = params or self . make_arguments ( None , [] , None , [] , None ) , returns = a , body = b , type_comment = tc , type_params = t or [] , decorator_list = [] , is_macro = isinstance ( n , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) ) if sys . version_info >= ( 3 , 12 ) else self . check_version ( ( 3 , 5 ) , "Async functions are" , AsyncFunctionDef ( name = n . string , args = params or self . make_arguments ( None , [] , None , [] , None ) , returns = a , body = b , type_comment = tc , decorator_list = [] , is_macro = isinstance ( n , MacroName ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , ) ) );
        self._reset(mark)
        return None;

    @memoize
    def else_block(self) -> Optional[list]:
        # else_block: invalid_else_stmt | &'else' macro_stmt | 'else' &&':' block
        mark = self._mark()
        if (
            self.call_invalid_rules
            and
            (self.invalid_else_stmt())
        ):
            return None  # pragma: no cover;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'else'))
            and
            (a := self.macro_stmt())
        ):
            return a;
        self._reset(mark)
        if (
            (self.expect('else'))
            and
            (self.expect_forced(self.expect(':'), "':'"))
            and
            (b := self.block())
        ):
            return b;
        self._reset(mark)
        return None;

    @memoize
    def try_stmt(self) -> Optional[ast . Try]:
        # try_stmt: invalid_try_stmt | &'try' macro_stmt | 'try' &&':' block finally_block | 'try' &&':' block except_block+ else_block? finally_block? | 'try' &&':' block except_star_block+ else_block? finally_block?
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            self.call_invalid_rules
            and
            (self.invalid_try_stmt())
        ):
            return None  # pragma: no cover;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'try'))
            and
            (a := self.macro_stmt())
        ):
            return a;
        self._reset(mark)
        if (
            (self.expect('try'))
            and
            (self.expect_forced(self.expect(':'), "':'"))
            and
            (b := self.block())
            and
            (f := self.finally_block())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Try ( body = b , handlers = [] , orelse = [] , finalbody = f , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (self.expect('try'))
            and
            (self.expect_forced(self.expect(':'), "':'"))
            and
            (b := self.block())
            and
            (ex := self._loop1_1022())
            and
            (el := self.else_block(),)
            and
            (f := self.finally_block(),)
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Try ( body = b , handlers = ex , orelse = el or [] , finalbody = f or [] , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (self.expect('try'))
            and
            (self.expect_forced(self.expect(':'), "':'"))
            and
            (b := self.block())
            and
            (ex := self._loop1_1023())
            and
            (el := self.else_block(),)
            and
            (f := self.finally_block(),)
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return self . check_version ( ( 3 , 11 ) , "Exception groups are" , ( ast . TryStar ( body = b , handlers = ex , orelse = el or [] , finalbody = f or [] , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset ) if sys . version_info >= ( 3 , 11 ) else None ) );
        self._reset(mark)
        return None;

    @memoize
    def finally_block(self) -> Optional[list]:
        # finally_block: invalid_finally_stmt | &'finally' macro_stmt | 'finally' &&':' block
        mark = self._mark()
        if (
            self.call_invalid_rules
            and
            (self.invalid_finally_stmt())
        ):
            return None  # pragma: no cover;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, 'finally'))
            and
            (a := self.macro_stmt())
        ):
            return a;
        self._reset(mark)
        if (
            (self.expect('finally'))
            and
            (self.expect_forced(self.expect(':'), "':'"))
            and
            (a := self.block())
        ):
            return a;
        self._reset(mark)
        return None;

    @memoize
    def import_name(self) -> Optional[Import]:
        # import_name: 'import' '!'? dotted_as_names
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (self.expect('import'))
            and
            (m := self.expect('!'),)
            and
            (a := self.dotted_as_names())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return Import ( names = a , is_macro = bool ( m ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        return None;

    @memoize
    def import_from(self) -> Optional[ImportFrom]:
        # import_from: 'from' '!'? (('.' | '...'))* dotted_name '!'? 'import' '!'? import_from_targets | 'from' '!'? (('.' | '...'))+ 'import' '!'? import_from_targets
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (self.expect('from'))
            and
            (f := self.expect('!'),)
            and
            (a := self._loop0_1024(),)
            and
            (b := self.dotted_name())
            and
            (mb := self.expect('!'),)
            and
            (self.expect('import'))
            and
            (i := self.expect('!'),)
            and
            (c := self.import_from_targets())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ImportFrom ( module = maybe_macro ( mb , b ) , names = c , level = self . extract_import_level ( a ) , is_macro = bool ( f or i ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (self.expect('from'))
            and
            (f := self.expect('!'),)
            and
            (a := self._loop1_1025())
            and
            (self.expect('import'))
            and
            (i := self.expect('!'),)
            and
            (b := self.import_from_targets())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ImportFrom ( names = b , level = self . extract_import_level ( a ) , is_macro = bool ( f or i ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset ) if sys . version_info >= ( 3 , 9 ) else ImportFrom ( module = None , names = b , level = self . extract_import_level ( a ) , is_macro = bool ( f or i ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        return None;

    @memoize
    def import_from_as_name(self) -> Optional[ast . alias]:
        # import_from_as_name: NAME '!'? ['as' NAME '!'?]
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (a := self.name())
            and
            (m := self.expect('!'),)
            and
            (b := self._tmp_1026(),)
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . alias ( name = maybe_macro ( m , a . string ) , asname = b , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        return None;

    @memoize
    def dotted_as_name(self) -> Optional[ast . alias]:
        # dotted_as_name: dotted_name '!'? ['as' NAME '!'?]
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (a := self.dotted_name())
            and
            (m := self.expect('!'),)
            and
            (b := self._tmp_1027(),)
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . alias ( name = maybe_macro ( m , a ) , asname = b , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        return None;

    @memoize_left_rec
    def dotted_name(self) -> Optional[str]:
        # dotted_name: dotted_name '.' (NAME | 'macro') | (NAME | 'macro')
        mark = self._mark()
        if (
            (a := self.dotted_name())
            and
            (self.expect('.'))
            and
            (b := self._tmp_1028())
        ):
            return a + "." + b . string;
        self._reset(mark)
        if (
            (a := self._tmp_1029())
        ):
            return a . string;
        self._reset(mark)
        return None;

    @memoize_left_rec
    def primary(self) -> Optional[Any]:
        # primary: primary '.' NAME | primary genexp | primary '(' arguments? ')' | primary '[' slices ']' | atom
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (a := self.primary())
            and
            (self.expect('.'))
            and
            (b := self.name())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Attribute ( value = a , attr = b . string , ctx = Load , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (a := self.primary())
            and
            (b := self.genexp())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Call ( func = a , args = [b] , keywords = [] , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (a := self.primary())
            and
            (self.expect('('))
            and
            (b := self.arguments(),)
            and
            (self.expect(')'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Call ( func = a , args = b [0] if b else [] , keywords = b [1] if b else [] , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , );
        self._reset(mark)
        if (
            (a := self.primary())
            and
            (self.expect('['))
            and
            (b := self.slices())
            and
            (self.expect(']'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Subscript ( value = a , slice = b , ctx = Load , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (atom := self.atom())
        ):
            return atom;
        self._reset(mark)
        return None;

    @memoize
    def atom(self) -> Optional[Any]:
        # atom: NAME !'!' | 'True' | 'False' | 'None' | &(STRING | FSTRING_START) strings | NUMBER | &'(' (tuple | group | genexp) | &'[' (list | listcomp) | &'{' (dict | set | dictcomp | setcomp) | '...' | macro_name '(' args_fragment? ')' | token_literal
        mark = self._mark()
        tok = self._tokenizer.peek()
        start_lineno, start_col_offset = tok.start
        if (
            (a := self.name())
            and
            (self.negative_lookahead(self.expect, '!'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Name ( id = a . string , ctx = Load , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (self.expect('True'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Constant ( value = True , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset ) if sys . version_info >= ( 3 , 9 ) else ast . Constant ( value = True , kind = None , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (self.expect('False'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Constant ( value = False , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset ) if sys . version_info >= ( 3 , 9 ) else ast . Constant ( value = False , kind = None , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (self.expect('None'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Constant ( value = None , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset ) if sys . version_info >= ( 3 , 9 ) else ast . Constant ( value = None , kind = None , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (self.positive_lookahead(self._tmp_1030, ))
            and
            (strings := self.strings())
        ):
            return strings;
        self._reset(mark)
        if (
            (a := self.number())
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Constant ( value = ast . literal_eval ( a . string ) , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset ) if sys . version_info >= ( 3 , 9 ) else ast . Constant ( value = ast . literal_eval ( a . string ) , kind = None , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, '('))
            and
            (_tmp_1031 := self._tmp_1031())
        ):
            return _tmp_1031;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, '['))
            and
            (_tmp_1032 := self._tmp_1032())
        ):
            return _tmp_1032;
        self._reset(mark)
        if (
            (self.positive_lookahead(self.expect, '{'))
            and
            (_tmp_1033 := self._tmp_1033())
        ):
            return _tmp_1033;
        self._reset(mark)
        if (
            (self.expect('...'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return ast . Constant ( value = Ellipsis , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset ) if sys . version_info >= ( 3 , 9 ) else ast . Constant ( value = Ellipsis , kind = None , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset );
        self._reset(mark)
        if (
            (a := self.macro_name())
            and
            (self.expect('('))
            and
            (args := self.args_fragment(),)
            and
            (self.expect(')'))
        ):
            tok = self._tokenizer.get_last_non_whitespace_token()
            end_lineno, end_col_offset = tok.end
            return MacroCall ( func = a . id , args = args or [] , keywords = [] , lineno=start_lineno, col_offset=start_col_offset, end_lineno=end_lineno, end_col_offset=end_col_offset , );
        self._reset(mark)
        if (
            (token_literal := self.token_literal())
        ):
            return token_literal;
        self._reset(mark)
        return None;

    @memoize
    def any_except_backtick(self) -> Optional[Any]:
        # any_except_backtick: !'`' ANY
        mark = self._mark()
        if (
            (self.negative_lookahead(self.expect, '`'))
            and
            (ANY := self.ANY())
        ):
            return ANY;
        self._reset(mark)
        return None;

    @memoize
    def token_literal(self) -> Optional[Any]:
        # token_literal: '`' '`' '`' any_except_backtick* '`' '`' '`' | '`' any_except_backtick* '`'
        mark = self._mark()
        if (
            (self.expect('`'))
            and
            (self.expect('`'))
            and
            (self.expect('`'))
            and
            (tokens := self._loop0_1034(),)
            and
            (self.expect('`'))
            and
            (self.expect('`'))
            and
            (self.expect('`'))
        ):
            return TokenLiteral ( tokens );
        self._reset(mark)
        if (
            (self.expect('`'))
            and
            (tokens := self._loop0_1035(),)
            and
            (self.expect('`'))
        ):
            return TokenLiteral ( tokens );
        self._reset(mark)
        return None;

    @memoize
    def invalid_def_raw(self) -> Optional[NoReturn]:
        # invalid_def_raw: 'async'? 'def' NAME '!'? type_params? '(' params? ')' ['->' expression] ':' NEWLINE !INDENT
        mark = self._mark()
        if (
            (self.expect('async'),)
            and
            (a := self.expect('def'))
            and
            (self.name())
            and
            (self.expect('!'),)
            and
            (self.type_params(),)
            and
            (self.expect('('))
            and
            (self.params(),)
            and
            (self.expect(')'))
            and
            (self._tmp_1036(),)
            and
            (self.expect(':'))
            and
            (self.expect('NEWLINE'))
            and
            (self.negative_lookahead(self.expect, 'INDENT'))
        ):
            return self . raise_indentation_error ( f"expected an indented block after function definition on line {a.start[0]}" );
        self._reset(mark)
        return None;

    @memoize
    def invalid_class_def_raw(self) -> Optional[NoReturn]:
        # invalid_class_def_raw: 'class' NAME '!'? type_params? ['(' arguments? ')'] NEWLINE | 'class' NAME '!'? type_params? ['(' arguments? ')'] ':' NEWLINE !INDENT
        mark = self._mark()
        if (
            (self.expect('class'))
            and
            (self.name())
            and
            (self.expect('!'),)
            and
            (self.type_params(),)
            and
            (self._tmp_1037(),)
            and
            (self.expect('NEWLINE'))
        ):
            return self . raise_syntax_error ( "expected ':'" );
        self._reset(mark)
        if (
            (a := self.expect('class'))
            and
            (self.name())
            and
            (self.expect('!'),)
            and
            (self.type_params(),)
            and
            (self._tmp_1038(),)
            and
            (self.expect(':'))
            and
            (self.expect('NEWLINE'))
            and
            (self.negative_lookahead(self.expect, 'INDENT'))
        ):
            return self . raise_indentation_error ( f"expected an indented block after class definition on line {a.start[0]}" );
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1001(self) -> Optional[Any]:
        # _tmp_1001: 'import' | 'from'
        mark = self._mark()
        if (
            (literal := self.expect('import'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('from'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1002(self) -> Optional[Any]:
        # _tmp_1002: 'def' | '@' | 'async'
        mark = self._mark()
        if (
            (literal := self.expect('def'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('@'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('async'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1003(self) -> Optional[Any]:
        # _tmp_1003: 'class' | '@'
        mark = self._mark()
        if (
            (literal := self.expect('class'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('@'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1004(self) -> Optional[Any]:
        # _tmp_1004: 'with' | 'async'
        mark = self._mark()
        if (
            (literal := self.expect('with'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('async'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1005(self) -> Optional[Any]:
        # _tmp_1005: 'for' | 'async'
        mark = self._mark()
        if (
            (literal := self.expect('for'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('async'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def _loop1_1006(self) -> Optional[Any]:
        # _loop1_1006: (!NEWLINE !INDENT !DEDENT ANY)
        mark = self._mark()
        children = []
        while (
            (_tmp_1039 := self._tmp_1039())
        ):
            children.append(_tmp_1039)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop1_1007(self) -> Optional[Any]:
        # _loop1_1007: (!braces !NEWLINE ANY)
        mark = self._mark()
        children = []
        while (
            (_tmp_1040 := self._tmp_1040())
        ):
            children.append(_tmp_1040)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop1_1008(self) -> Optional[Any]:
        # _loop1_1008: unparsed_block
        mark = self._mark()
        children = []
        while (
            (unparsed_block := self.unparsed_block())
        ):
            children.append(unparsed_block)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop1_1009(self) -> Optional[Any]:
        # _loop1_1009: unparsed_block
        mark = self._mark()
        children = []
        while (
            (unparsed_block := self.unparsed_block())
        ):
            children.append(unparsed_block)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop1_1010(self) -> Optional[Any]:
        # _loop1_1010: (!braces !':' !NEWLINE ANY)
        mark = self._mark()
        children = []
        while (
            (_tmp_1041 := self._tmp_1041())
        ):
            children.append(_tmp_1041)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_1011(self) -> Optional[Any]:
        # _tmp_1011: NAME | !forbidden_macro_keywords KEYWORD
        mark = self._mark()
        if (
            (name := self.name())
        ):
            return name;
        self._reset(mark)
        if (
            (self.negative_lookahead(self.forbidden_macro_keywords, ))
            and
            (KEYWORD := self.KEYWORD())
        ):
            return KEYWORD;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1012(self) -> Optional[Any]:
        # _tmp_1012: '@' dec_macro NEWLINE
        mark = self._mark()
        if (
            (self.expect('@'))
            and
            (f := self.dec_macro())
            and
            (self.expect('NEWLINE'))
        ):
            return f;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1013(self) -> Optional[Any]:
        # _tmp_1013: '@' dec_maybe_call NEWLINE
        mark = self._mark()
        if (
            (self.expect('@'))
            and
            (f := self.dec_maybe_call())
            and
            (self.expect('NEWLINE'))
        ):
            return f;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1014(self) -> Optional[Any]:
        # _tmp_1014: '@' named_expression NEWLINE
        mark = self._mark()
        if (
            (self.expect('@'))
            and
            (f := self.named_expression())
            and
            (self.expect('NEWLINE'))
        ):
            return f;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1015(self) -> Optional[Any]:
        # _tmp_1015: '(' arguments? ')'
        mark = self._mark()
        if (
            (self.expect('('))
            and
            (z := self.arguments(),)
            and
            (self.expect(')'))
        ):
            return z;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1016(self) -> Optional[Any]:
        # _tmp_1016: '(' arguments? ')'
        mark = self._mark()
        if (
            (self.expect('('))
            and
            (z := self.arguments(),)
            and
            (self.expect(')'))
        ):
            return z;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1017(self) -> Optional[Any]:
        # _tmp_1017: 'def' | 'async'
        mark = self._mark()
        if (
            (literal := self.expect('def'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('async'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1018(self) -> Optional[Any]:
        # _tmp_1018: '->' expression
        mark = self._mark()
        if (
            (self.expect('->'))
            and
            (z := self.expression())
        ):
            return z;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1019(self) -> Optional[Any]:
        # _tmp_1019: '->' expression
        mark = self._mark()
        if (
            (self.expect('->'))
            and
            (z := self.expression())
        ):
            return z;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1020(self) -> Optional[Any]:
        # _tmp_1020: '->' expression
        mark = self._mark()
        if (
            (self.expect('->'))
            and
            (z := self.expression())
        ):
            return z;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1021(self) -> Optional[Any]:
        # _tmp_1021: '->' expression
        mark = self._mark()
        if (
            (self.expect('->'))
            and
            (z := self.expression())
        ):
            return z;
        self._reset(mark)
        return None;

    @memoize
    def _loop1_1022(self) -> Optional[Any]:
        # _loop1_1022: except_block
        mark = self._mark()
        children = []
        while (
            (except_block := self.except_block())
        ):
            children.append(except_block)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop1_1023(self) -> Optional[Any]:
        # _loop1_1023: except_star_block
        mark = self._mark()
        children = []
        while (
            (except_star_block := self.except_star_block())
        ):
            children.append(except_star_block)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop0_1024(self) -> Optional[Any]:
        # _loop0_1024: ('.' | '...')
        mark = self._mark()
        children = []
        while (
            (_tmp_1042 := self._tmp_1042())
        ):
            children.append(_tmp_1042)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop1_1025(self) -> Optional[Any]:
        # _loop1_1025: ('.' | '...')
        mark = self._mark()
        children = []
        while (
            (_tmp_1043 := self._tmp_1043())
        ):
            children.append(_tmp_1043)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_1026(self) -> Optional[Any]:
        # _tmp_1026: 'as' NAME '!'?
        mark = self._mark()
        if (
            (self.expect('as'))
            and
            (z := self.name())
            and
            (n := self.expect('!'),)
        ):
            return maybe_macro ( n , z . string );
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1027(self) -> Optional[Any]:
        # _tmp_1027: 'as' NAME '!'?
        mark = self._mark()
        if (
            (self.expect('as'))
            and
            (z := self.name())
            and
            (n := self.expect('!'),)
        ):
            return maybe_macro ( n , z . string );
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1028(self) -> Optional[Any]:
        # _tmp_1028: NAME | 'macro'
        mark = self._mark()
        if (
            (name := self.name())
        ):
            return name;
        self._reset(mark)
        if (
            (literal := self.expect('macro'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1029(self) -> Optional[Any]:
        # _tmp_1029: NAME | 'macro'
        mark = self._mark()
        if (
            (name := self.name())
        ):
            return name;
        self._reset(mark)
        if (
            (literal := self.expect('macro'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1030(self) -> Optional[Any]:
        # _tmp_1030: STRING | FSTRING_START
        mark = self._mark()
        if (
            (string := self.string())
        ):
            return string;
        self._reset(mark)
        if (
            (fstring_start := self.fstring_start())
        ):
            return fstring_start;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1031(self) -> Optional[Any]:
        # _tmp_1031: tuple | group | genexp
        mark = self._mark()
        if (
            (tuple := self.tuple())
        ):
            return tuple;
        self._reset(mark)
        if (
            (group := self.group())
        ):
            return group;
        self._reset(mark)
        if (
            (genexp := self.genexp())
        ):
            return genexp;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1032(self) -> Optional[Any]:
        # _tmp_1032: list | listcomp
        mark = self._mark()
        if (
            (list := self.list())
        ):
            return list;
        self._reset(mark)
        if (
            (listcomp := self.listcomp())
        ):
            return listcomp;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1033(self) -> Optional[Any]:
        # _tmp_1033: dict | set | dictcomp | setcomp
        mark = self._mark()
        if (
            (dict := self.dict())
        ):
            return dict;
        self._reset(mark)
        if (
            (set := self.set())
        ):
            return set;
        self._reset(mark)
        if (
            (dictcomp := self.dictcomp())
        ):
            return dictcomp;
        self._reset(mark)
        if (
            (setcomp := self.setcomp())
        ):
            return setcomp;
        self._reset(mark)
        return None;

    @memoize
    def _loop0_1034(self) -> Optional[Any]:
        # _loop0_1034: any_except_backtick
        mark = self._mark()
        children = []
        while (
            (any_except_backtick := self.any_except_backtick())
        ):
            children.append(any_except_backtick)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _loop0_1035(self) -> Optional[Any]:
        # _loop0_1035: any_except_backtick
        mark = self._mark()
        children = []
        while (
            (any_except_backtick := self.any_except_backtick())
        ):
            children.append(any_except_backtick)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_1036(self) -> Optional[Any]:
        # _tmp_1036: '->' expression
        mark = self._mark()
        if (
            (literal := self.expect('->'))
            and
            (expression := self.expression())
        ):
            return [literal, expression];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1037(self) -> Optional[Any]:
        # _tmp_1037: '(' arguments? ')'
        mark = self._mark()
        if (
            (literal := self.expect('('))
            and
            (opt := self.arguments(),)
            and
            (literal_1 := self.expect(')'))
        ):
            return [literal, opt, literal_1];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1038(self) -> Optional[Any]:
        # _tmp_1038: '(' arguments? ')'
        mark = self._mark()
        if (
            (literal := self.expect('('))
            and
            (opt := self.arguments(),)
            and
            (literal_1 := self.expect(')'))
        ):
            return [literal, opt, literal_1];
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1039(self) -> Optional[Any]:
        # _tmp_1039: !NEWLINE !INDENT !DEDENT ANY
        mark = self._mark()
        if (
            (self.negative_lookahead(self.expect, 'NEWLINE'))
            and
            (self.negative_lookahead(self.expect, 'INDENT'))
            and
            (self.negative_lookahead(self.expect, 'DEDENT'))
            and
            (ANY := self.ANY())
        ):
            return ANY;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1040(self) -> Optional[Any]:
        # _tmp_1040: !braces !NEWLINE ANY
        mark = self._mark()
        if (
            (self.negative_lookahead(self.braces, ))
            and
            (self.negative_lookahead(self.expect, 'NEWLINE'))
            and
            (ANY := self.ANY())
        ):
            return ANY;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1041(self) -> Optional[Any]:
        # _tmp_1041: !braces !':' !NEWLINE ANY
        mark = self._mark()
        if (
            (self.negative_lookahead(self.braces, ))
            and
            (self.negative_lookahead(self.expect, ':'))
            and
            (self.negative_lookahead(self.expect, 'NEWLINE'))
            and
            (ANY := self.ANY())
        ):
            return ANY;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1042(self) -> Optional[Any]:
        # _tmp_1042: '.' | '...'
        mark = self._mark()
        if (
            (literal := self.expect('.'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('...'))
        ):
            return literal;
        self._reset(mark)
        return None;

    @memoize
    def _tmp_1043(self) -> Optional[Any]:
        # _tmp_1043: '.' | '...'
        mark = self._mark()
        if (
            (literal := self.expect('.'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('...'))
        ):
            return literal;
        self._reset(mark)
        return None;

    KEYWORDS = tuple(set([*('False', 'None', 'True', 'as', 'assert', 'async', 'break', 'class', 'continue', 'def', 'del', 'else', 'finally', 'for', 'from', 'global', 'if', 'import', 'macro', 'nonlocal', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield'), *getattr(PythonParser, 'KEYWORDS', [])]))
    SOFT_KEYWORDS = tuple(set([*('type',), *getattr(PythonParser, 'SOFT_KEYWORDS', [])]))
    RULES = tuple(set(['KEYWORD', 'ANY', 'braces', 'simple_stmt', 'compound_stmt', 'unparsed_atoms', 'unparsed_balanced', 'unparsed_line', 'unparsed_block', 'args_fragment', 'suite_fragment', 'raw_macro_stmt_args', 'macro_stmt_args', 'macro_stmt', 'forbidden_macro_keywords', 'macro_name', 'maybe_macro', 'decorator', 'dec_macro', 'class_def', 'class_def_raw', 'unparsed_class_def', 'function_def', 'function_def_raw', 'unparsed_function_def', 'else_block', 'try_stmt', 'finally_block', 'import_name', 'import_from', 'import_from_as_name', 'dotted_as_name', 'dotted_name', 'primary', 'atom', 'any_except_backtick', 'token_literal', 'invalid_def_raw', 'invalid_class_def_raw', *getattr(PythonParser, 'KEYWORDS', [])]))

    def __init__(self, 
            tokenizer: Tokenizer, *,
            verbose: bool = False,
            filename: str = "<unknown>",
            py_version: Optional[tuple] = None):
        super().__init__(tokenizer, verbose=verbose, filename=filename, py_version=py_version)
