# Minimal patch grammar for declarative macros

@class MacroPegParser
@extends "peg.py"
@base PegParser
@subheader"""
import textwrap
from magic_codec.parser.peg import *
from tokenize import TokenInfo

def source_range(tokenizer, lineno, col_offset, end_lineno, end_col_offset):
    lines = tokenizer.get_lines(list(range(lineno, end_lineno + 1)))
    lines[-1] = lines[-1][:end_col_offset - 1]
    lines[0] = lines[0][col_offset + 1:]

    # strip leading whitespace
    data = ''.join(lines).lstrip(' ')
    if data[0] == '\\n':
        data = data[1:]
    return textwrap.dedent(data)
"""
@trailer''

action[str]: a="{" ~ target_atoms b="}" { source_range(self._tokenizer, LOCATIONS) }
