# Patch grammar for macro support

# @import "python.peg"
@class MacroPythonParser
@extends "python_parser.py"
@base PythonParser
@subheader'''
from magic_codec.macro.parser import *
from magic_codec.macro.macro_ast import *
from token import NAME, ENDMARKER
from magic_codec.grammar.python_parser import PythonParser
'''

# META RULES
# ==========

KEYWORD: ~ { 
        (self._tokenizer.getnext() 
        if (tok := self._tokenizer.peek()).type == NAME 
        and tok.string in self.KEYWORDS else None)
    }
# this hack is equivalent to:
# KEYWORD:
#     | 'False' | 'None' | 'True' | 'and' | 'as' | 'assert' | 'async' | 'await' | 'break' | 'class' | 'continue' 
#     | 'def' | 'del' | 'elif' | 'else' | 'except' | 'finally' | 'for' | 'from' | 'global' | 'if' | 'import' 
#     | 'in' | 'is' | 'lambda' | 'nonlocal' | 'not' | 'or' | 'pass' | 'raise' | 'return' | 'try' | 'while' 
#     | 'with' | 'yield' | 'macro'

ANY: ~ { t if (t:=self._tokenizer.getnext()).type != 0 else None }
# this hack is equivalent to:
# ANY:
#     | OP | NAME | STRING | NUMBER 
#     | keyword | SOFT_KEYWORD 
#     | NEWLINE 
#     | TYPE_COMMENT 
#     | FSTRING_START | FSTRING_MIDDLE | FSTRING_END 


braces: '(' | ')' | '[' | ']' | '{' | '}'

# GENERAL STATEMENTS
# ==================

compound_stmt:
    | macro_stmt
    | &('def' | '@' | 'async') function_def
    | &'if' if_stmt
    | &('class' | '@') class_def
    | &('with' | 'async') with_stmt
    | &('for' | 'async') for_stmt
    | &'try' try_stmt
    | &'while' while_stmt
    | match_stmt

# Unparsed elements
# -----------------

unparsed_atoms:
    | a=(!NEWLINE !INDENT !DEDENT ANY)+ { a }

unparsed_balanced:
    | '(' unparsed_balanced? ')' unparsed_balanced?
    | '[' unparsed_balanced? ']' unparsed_balanced?
    | '{' unparsed_balanced? '}' unparsed_balanced?
    | (!braces !NEWLINE ANY)+ unparsed_balanced? 

unparsed_line:
    | unparsed_atoms NEWLINE

unparsed_block:
    | INDENT unparsed_block+ DEDENT
    | unparsed_line

# Fragments
# ---------

args_fragment:
    | a=unparsed_balanced { self.make_fragment(a) }

suite_fragment:
    | NEWLINE INDENT a=unparsed_block+ DEDENT { self.make_fragment(a) }
    | a=unparsed_line { self.make_fragment(a) }


# Macro statement
# ---------------
raw_macro_stmt_args:
    | a='(' b=unparsed_balanced? c=')' raw_macro_stmt_args? 
    | a='[' b=unparsed_balanced? c=']' raw_macro_stmt_args?
    | a='{' b=unparsed_balanced? c='}' raw_macro_stmt_args?
    | a=(!braces !':' !NEWLINE ANY)+ raw_macro_stmt_args?

macro_stmt_args:
    | a=raw_macro_stmt_args { self.make_fragment(a) }


macro_stmt[MacroCall]:
    # | a=macro_name [macro_stmt_args] ':' unparsed_line INDENT { self.raise_indentation_error("unexpected indented block") }
    | a=macro_name ':' b=suite_fragment { MacroCall(a, args=b, LOCATIONS) }
    | a=macro_name h=macro_stmt_args ':' b=suite_fragment {
        MacroCall(MacroCall(a, args=h, LOCATIONS), b, LOCATIONS)
     }

 # Common elements
 # ---------------

# macros may not redefine `import!` or `from!` - these have meaning to the preprocessor
forbidden_macro_keywords: 'import' | 'from'
macro_name:
    | a=(NAME| !forbidden_macro_keywords KEYWORD) '!' { MacroName(id=a.string, ctx=Load, LOCATIONS) }

maybe_macro:
    | macro_name
    | NAME

decorator:
    | a=('@' f=dec_macro NEWLINE { f }) { a }
    | a=('@' f=dec_maybe_call NEWLINE { f }) { a }
    | a=('@' f=named_expression NEWLINE { f }) { self.check_version((3, 9), "Generic decorator are",  a) }
dec_macro:
    | a=macro_name '(' args=[args_fragment] ')' {
        MacroCall(func=a.id, args=args or [], keywords=[], LOCATIONS)
     }
    | macro_name
    # this makes `macro` a keyword that's only usable in decorators
    | a='macro' '(' z=[arguments] ')' {
        ast.Call(func=a, args=z[0] if z else [], keywords=z[1] if z else [], LOCATIONS)
     }
    | a='macro' { ast.Name(id=a.string, ctx=Load, LOCATIONS) }


# Class definitions
# -----------------

class_def[Union[ClassDef]]:
    | a=decorators &'class' {
        self.conditional_parse_def(a, self.unparsed_class_def, self.class_def_raw)
     }
    | class_def_raw

class_def_raw[Union[ClassDef]]:
    | invalid_class_def_raw
    | 'class' a=maybe_macro t=[type_params] b=['(' z=[arguments] ')' { z }] ':' c=block {
        (
            ClassDef(
                a.string,
                bases=b[0] if b else [],
                keywords=b[1] if b else [],
                body=c,
                decorator_list=[],
                type_params=t or [],
                is_macro=isinstance(a, MacroName),
                LOCATIONS,
            )
            if sys.version_info >= (3, 12) else
            ClassDef(
                a.string,
                bases=b[0] if b else [],
                keywords=b[1] if b else [],
                body=c,
                decorator_list=[],
                is_macro=isinstance(a, MacroName),
                LOCATIONS,
            )
        )
     }

unparsed_class_def[Union[ClassDef]]:
    | invalid_class_def_raw
    | 'class' a=maybe_macro t=[type_params] b=['(' z=[arguments] ')' { z }] ':' c=suite_fragment {
        (
            ClassDef(
                a.string,
                bases=b[0] if b else [],
                keywords=b[1] if b else [],
                body=c,
                decorator_list=[],
                type_params=t or [],
                is_macro=isinstance(a, MacroName),
                LOCATIONS,
            )
            if sys.version_info >= (3, 12) else
            ClassDef(
                a.string,
                bases=b[0] if b else [],
                keywords=b[1] if b else [],
                body=c,
                decorator_list=[],
                is_macro=isinstance(a, MacroName),
                LOCATIONS,
            )
        )
     }

# Function definitions
# --------------------

function_def[Union[FunctionDef, AsyncFunctionDef]]:
    | d=decorators &('def'|'async') { self.conditional_parse_def(d, self.unparsed_function_def, self.function_def_raw) }
    | function_def_raw

function_def_raw[Union[FunctionDef, AsyncFunctionDef]]:
    | invalid_def_raw
    | 'def' n=maybe_macro t=[type_params] '(' params=[params] ')' a=['->' z=expression { z }] ':' tc=[func_type_comment] b=block {
        (
            FunctionDef(
                name=n.string,
                args=params or self.make_arguments(None, [], None, [], None),
                returns=a,
                body=b,
                type_comment=tc,
                type_params=t or [],
                decorator_list=[],
                is_macro=isinstance(n, MacroName),
                LOCATIONS,
            ) if sys.version_info >= (3, 12) else
            FunctionDef(
                name=n.string,
                args=params or self.make_arguments(None, [], None, [], None),
                returns=a,
                body=b,
                type_comment=tc,
                decorator_list=[],
                is_macro=isinstance(n, MacroName),
                LOCATIONS,
            )
        )
     }
    | 'async' 'def' n=maybe_macro t=[type_params] '(' params=[params] ')' a=['->' z=expression { z }] ':' tc=[func_type_comment] b=block {
       (
            self.check_version(
                (3, 5),
                "Async functions are",
                AsyncFunctionDef(
                    name=n.string,
                    args=params or self.make_arguments(None, [], None, [], None),
                    returns=a,
                    body=b,
                    type_comment=tc,
                    type_params=t or [],
                    decorator_list=[],
                    is_macro=isinstance(n, MacroName),
                    LOCATIONS,
                )
            ) if sys.version_info >= (3, 12) else
            self.check_version(
                (3, 5),
                "Async functions are",
                AsyncFunctionDef(
                    name=n.string,
                    args=params or self.make_arguments(None, [], None, [], None),
                    returns=a,
                    body=b,
                    type_comment=tc,
                    decorator_list=[],
                    is_macro=isinstance(n, MacroName),
                    LOCATIONS,
                )
            )
       )
     }

unparsed_function_def[Union[FunctionDef, AsyncFunctionDef]]:
    | invalid_def_raw
    | 'def' n=maybe_macro t=[type_params] '(' params=[params] ')' a=['->' z=expression { z }] ':' tc=[func_type_comment] b=suite_fragment {
        (
            FunctionDef(
                name=n.string,
                args=params or self.make_arguments(None, [], None, [], None),
                returns=a,
                body=b,
                type_comment=tc,
                type_params=t or [],
                decorator_list=[],
                is_macro=isinstance(n, MacroName),
                LOCATIONS,
            ) if sys.version_info >= (3, 12) else
            FunctionDef(
                name=n.string,
                args=params or self.make_arguments(None, [], None, [], None),
                returns=a,
                body=b,
                type_comment=tc,
                is_macro=isinstance(n, MacroName),
                LOCATIONS,
            )
        )
     }
    | 'async' 'def' n=maybe_macro t=[type_params] &&'(' params=[params] ')' a=['->' z=expression { z }] ':' tc=[func_type_comment] b=suite_fragment {
       (
            self.check_version(
                (3, 5),
                "Async functions are",
                AsyncFunctionDef(
                    name=n.string,
                    args=params or self.make_arguments(None, [], None, [], None),
                    returns=a,
                    body=b,
                    type_comment=tc,
                    type_params=t or [],
                    decorator_list=[],
                    is_macro=isinstance(n, MacroName),
                    LOCATIONS,
                )
            ) if sys.version_info >= (3, 12) else
            self.check_version(
                (3, 5),
                "Async functions are",
                AsyncFunctionDef(
                    name=n.string,
                    args=params or self.make_arguments(None, [], None, [], None),
                    returns=a,
                    body=b,
                    type_comment=tc,
                    decorator_list=[],
                    is_macro=isinstance(n, MacroName),
                    LOCATIONS,
                )
            )
       )
     }


# If statement
# ------------

else_block[list]:
    | invalid_else_stmt
    | &'else' a=macro_stmt { a }
    | 'else' &&':' b=block { b }

# Try statement
# -------------
try_stmt[ast.Try]:
    | invalid_try_stmt
    | &'try' a=macro_stmt { a }
    | 'try' &&':' b=block f=finally_block{
        ast.Try(body=b, handlers=[], orelse=[], finalbody=f, LOCATIONS)
     }
    | 'try' &&':' b=block ex=except_block+ el=[else_block] f=[finally_block] {
        ast.Try(body=b, handlers=ex, orelse=el or [], finalbody=f or [], LOCATIONS)
     }
    | 'try' &&':' b=block ex=except_star_block+ el=[else_block] f=[finally_block] {
        self.check_version(
            (3, 11),
            "Exception groups are",
            (
                ast.TryStar(body=b, handlers=ex, orelse=el or [], finalbody=f or [], LOCATIONS)
                if sys.version_info >= (3, 11)
                else None
            )
        )
     }

# Except statement
# ----------------
finally_block[list]:
    | invalid_finally_stmt
    | &'finally' a=macro_stmt { a }
    | 'finally' &&':' a=block { a }


# Import statements
# -----------------
import_name[Import]: 'import' m=['!'] a=dotted_as_names { Import(names=a, is_macro=bool(m), LOCATIONS) }

# note below: the ('.' | '...') is necessary because '...' is tokenized as ELLIPSIS
import_from[ImportFrom]:
    | 'from' f=['!'] a=('.' | '...')* b=dotted_name mb=['!'] 'import' i=['!'] c=import_from_targets {
        ImportFrom(module=maybe_macro(mb, b), names=c, level=self.extract_import_level(a), is_macro=bool(f or i), LOCATIONS)
     }
    | 'from' f=['!'] a=('.' | '...')+ 'import' i=['!'] b=import_from_targets {
        ImportFrom(names=b, level=self.extract_import_level(a), is_macro=bool(f or i), LOCATIONS)
        if sys.version_info >= (3, 9) else
        ImportFrom(module=None, names=b, level=self.extract_import_level(a), is_macro=bool(f or i), LOCATIONS)
     }

import_from_as_name[ast.alias]:
    | a=NAME m=['!'] b=['as' z=NAME n=['!'] { maybe_macro(n, z.string) }] { 
        ast.alias(name=maybe_macro(m, a.string), asname=b, LOCATIONS) 
     }

dotted_as_name[ast.alias]:
    | a=dotted_name m=['!'] b=['as' z=NAME n=['!'] { maybe_macro(n, z.string) }] { 
        ast.alias(name=maybe_macro(m, a), asname=b, LOCATIONS) 
     }
# allow "macro" in imports
dotted_name[str]:
    | a=dotted_name '.' b=(NAME | 'macro') { a + "." + b.string }
    | a=(NAME | 'macro') { a.string }

# Primary elements
# ----------------

primary:
    | a=primary '.' b=NAME { ast.Attribute(value=a, attr=b.string, ctx=Load, LOCATIONS) }
    | a=primary b=genexp { ast.Call(func=a, args=[b], keywords=[], LOCATIONS) }
    | a=primary '(' b=[arguments] ')' {
        ast.Call(
            func=a,
            args=b[0] if b else [],
            keywords=b[1] if b else [],
            LOCATIONS,
        )
     }
    | a=primary '[' b=slices ']' { ast.Subscript(value=a, slice=b, ctx=Load, LOCATIONS) }
    | atom

atom:
    # macro calls are atoms rather than primary to allow foo!()() etc
    | a=NAME !'!' { ast.Name(id=a.string, ctx=Load, LOCATIONS) }
    | 'True' {
        ast.Constant(value=True, LOCATIONS)
        if sys.version_info >= (3, 9) else
        ast.Constant(value=True, kind=None, LOCATIONS)
     }
    | 'False' {
        ast.Constant(value=False, LOCATIONS)
        if sys.version_info >= (3, 9) else
        ast.Constant(value=False, kind=None, LOCATIONS)
     }
    | 'None' {
        ast.Constant(value=None, LOCATIONS)
        if sys.version_info >= (3, 9) else
        ast.Constant(value=None, kind=None, LOCATIONS)
     }
    | &(STRING|FSTRING_START) strings
    | a=NUMBER {
        ast.Constant(value=ast.literal_eval(a.string), LOCATIONS)
        if sys.version_info >= (3, 9) else
        ast.Constant(value=ast.literal_eval(a.string), kind=None, LOCATIONS)
     }
    | &'(' (tuple | group | genexp)
    | &'[' (list | listcomp)
    | &'{' (dict | set | dictcomp | setcomp)
    | '...' {
        ast.Constant(value=Ellipsis, LOCATIONS)
        if sys.version_info >= (3, 9) else
        ast.Constant(value=Ellipsis, kind=None, LOCATIONS)
     }
    | a=macro_name '(' args=[args_fragment] ')' {
        MacroCall(
            func=a.id,
            args=args or [],
            keywords=[],
            LOCATIONS,
        )
     }
    | token_literal

# Token Literal
# -------------

any_except_backtick: !'`' ANY

token_literal:
    | '`' '`' '`' tokens=any_except_backtick* '`' '`' '`' { TokenLiteral(tokens) }
    | '`' tokens=any_except_backtick* '`' { TokenLiteral(tokens) }


# Invalid Rules
# -------------

invalid_def_raw[NoReturn]:
    | ['async'] a='def' NAME ['!'] [type_params] '(' [params] ')' ['->' expression] ':' NEWLINE !INDENT {
        self.raise_indentation_error(
            f"expected an indented block after function definition on line {a.start[0]}"
        )
     }
invalid_class_def_raw[NoReturn]:
    | 'class' NAME ['!'] [type_params] ['(' [arguments] ')'] NEWLINE { self.raise_syntax_error("expected ':'") }
    | a='class' NAME  ['!'] [type_params] ['(' [arguments] ')'] ':' NEWLINE !INDENT {
        self.raise_indentation_error(
            f"expected an indented block after class definition on line {a.start[0]}"
        )
     }