@class TestParser
@subheader'''
from magic_codec.macros.parser import *
from magic_codec.macros.macro_ast import *
'''

start:
    | a=test_stmt+ {ast.Module(a)}

test_stmt:
    # | a=NAME ':' b=unparsed_suite { MacroStmt(a.string, b) }
    # | a=NAME '(' b=args_fragment ')' { ast.Call(a, args=b) }
    | macro_stmt

KEYWORD: ~ { 
        (self._tokenizer.getnext() 
        if (tok := self._tokenizer.peek()).type == token.NAME 
        and tok.string in self.KEYWORDS else None)
    }
ANY: !ENDMARKER { self._tokenizer.getnext() }

unparsed_atoms:
    | a=(!NEWLINE !INDENT !DEDENT ANY)+ { a }

braces: '(' | ')' | '[' | ']' | '{' | '}'

unparsed_balanced(memo):
    | '(' unparsed_balanced? ')' unparsed_balanced?
    | '[' unparsed_balanced? ']' unparsed_balanced?
    | '{' unparsed_balanced? '}' unparsed_balanced?
    | (!braces !NEWLINE ANY)+ unparsed_balanced? 



unparsed_line:
    | unparsed_atoms NEWLINE

unparsed_block:
    | INDENT unparsed_block+ DEDENT
    | unparsed_line

## Fragments

args_fragment:
    | a=unparsed_balanced { self.make_fragment(a) }

block_fragment:
    | NEWLINE INDENT a=unparsed_block+ DEDENT { self.make_fragment(a) }
    | a=unparsed_line { self.make_fragment(a) }


forbidden_macro_keywords: 'import' | 'from'
macro_name:
    | a=(NAME| !forbidden_macro_keywords KEYWORD) '!' { MacroName(id=a.string, ctx=Load, LOCATIONS) }

# only allow ':' inside braces, parenthesis and brackets
raw_macro_stmt_args:
    | a='(' b=unparsed_balanced? c=')' raw_macro_stmt_args? 
    | a='[' b=unparsed_balanced? c=']' raw_macro_stmt_args?
    | a='{' b=unparsed_balanced? c='}' raw_macro_stmt_args?
    | a=(!'[' !']' !':' !NEWLINE ANY)+ raw_macro_stmt_args?

macro_stmt_args:
    | a=raw_macro_stmt_args { self.make_fragment(a) }

macro_stmt[MacroStmt]:
    | a=macro_name [macro_stmt_args] ':' unparsed_line INDENT { self.raise_indentation_error("unexpected indented block") }
    | a=macro_name ':' b=block_fragment { MacroCall(a, args=b, LOCATIONS) }
    | a=macro_name h=macro_stmt_args ':' b=block_fragment {
        MacroCall(MacroCall(a, args=h, LOCATIONS), b, LOCATIONS)
     }



# NAME:'suite_nested' OP:':'             
# NEWLINE:'\n'
# INDENT:'    '
#     NUMBER:'3'
#     NEWLINE:'\n'
#     INDENT:'        '
#         NUMBER:'4'
#         NEWLINE:'\n'
#     DEDENT:''
#     NUMBER:'3'
#     NEWLINE:''
# DEDENT:''
# ENDMARKER:''

# same_line: print(x)

# suite_single: 
#     print(x)

# suite_multi: 
#     print(x)
#     print(y)

# suite_nested: 
#     print(x)
#         test()
#         foo()
#     print(y)